# Generated by Django 5.2.10 on 2026-02-02 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.pricelist'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='products.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization', 'is_active'], name='categories_organiz_db70f3_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='categories_parent__7983b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='product_var_product_017fde_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='product_var_sku_3a95f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('organization', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'variant', 'price_list', 'min_quantity')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('organization', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_active'], name='products_organiz_83e089_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'category'], name='products_organiz_45f512_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_sku_fe2039_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='products_barcode_d008ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'sku'), ('organization', 'slug')},
        ),
    ]
