# Generated by Django 5.2.10 on 2026-02-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'slug'), name='unique_brand_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'name'), name='unique_brand_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'slug'), name='unique_category_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'name'), name='unique_category_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('organization', 'symbol'), name='unique_unit_symbol_per_org'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_unit_name_per_org'),
        ),
    ]
