# Generated by Django 5.2.10 on 2026-02-03 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options'),
        ('products', '0003_alter_brand_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'sku'), name='unique_product_sku_per_org'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'slug'), name='unique_product_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'sku'), name='unique_variant_sku_per_org'),
        ),
    ]
