# Generated by Django 5.2.14 on 2026-08-14 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('products', '0008_product_sync_updated_at_product_synced_from_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_auto_unpacking',
            field=models.BooleanField(default=True, help_text="Autorise l'ouverture automatique d'un conditionnement lorsque le stock à l'unité est insuffisant pour servir une vente au détail."),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_unit',
            field=models.ForeignKey(blank=True, help_text='Unité de gros (paquet, carton, casier…).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaged_products', to='products.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_mode',
            field=models.CharField(choices=[('retail_only', 'Vente au détail uniquement'), ('wholesale_only', 'Vente en gros uniquement'), ('wholesale_and_retail', 'Vente en gros et au détail')], default='retail_only', help_text='Forme sous laquelle ce produit est vendu.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_package',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'unités de détail contenues dans un conditionnement.", null=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('units_per_package__isnull', True), ('units_per_package__gte', 2), _connector='OR'), name='product_units_per_package_gte_2'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_mode', 'retail_only'), ('units_per_package__isnull', False), _connector='OR'), name='product_packaging_requires_units_per_package'),
        ),
    ]
