# Generated by Django 5.2.14 on 2026-08-14 09:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_allow_auto_unpacking_product_packaging_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat d'un conditionnement entier. Confort de saisie pour le marchand qui achète au carton ; `cost_price` (à l'unité) reste la valeur utilisée pour le coût moyen pondéré et les marges.", max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
