# Generated by Django 5.2.14 on 2026-08-28 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('products', '0010_product_package_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='products_organiz_5d3d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='product_var_organiz_2fc794_idx'),
        ),
    ]
