# Generated by Django 5.2.10 on 2026-02-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_register_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_printed',
            field=models.BooleanField(default=False),
        ),
    ]
