# Generated by Django 6.0.1 on 2026-05-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_loyalty_redemption_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stock_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
