# Generated by Django 6.0.1 on 2026-05-27 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_supplier_unused_fields'),
        ('inventory', '0009_stockbatch_location'),
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('products', '0007_update_category_parent_constraints'),
        ('sales', '0009_add_sale_stock_reserved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', '-sale_date'], name='sales_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'status', 'amount_due'], name='sales_org_status_due_idx'),
        ),
    ]
