# Generated by Django 5.2.14 on 2026-08-03 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_customer_customer_org_created_idx'),
        ('inventory', '0011_stock_stock_org_warehouse_idx'),
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('products', '0008_product_sync_updated_at_product_synced_from_client_and_more'),
        ('sales', '0012_payment_sync_updated_at_payment_synced_from_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registersession',
            index=models.Index(fields=['register', 'status', '-closed_at'], name='regsess_status_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'status', 'sale_date'], name='sales_org_status_date_idx'),
        ),
    ]
