# Generated by Django 5.2.14 on 2026-08-03 22:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('sales', '0013_registersession_regsess_status_closed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tendered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=15),
        ),
        migrations.CreateModel(
            name='RegisterSessionCurrencyBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('counted_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Montant réel compté dans cette devise à la fermeture.', max_digits=15, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_balances', to='sales.registersession')),
            ],
            options={
                'db_table': 'register_session_currency_balances',
                'ordering': ['currency'],
                'constraints': [models.UniqueConstraint(fields=('session', 'currency'), name='unique_session_currency_balance')],
            },
        ),
    ]
