# Generated by Django 6.0.1 on 2026-08-09 22:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_backfill_multicurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=12, default=Decimal('1.000000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=12, default=Decimal('1.000000'), max_digits=20),
        ),
    ]
