# Generated by Django 5.2.14 on 2026-08-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_payment_exchange_rate_alter_sale_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='sale',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
