# Generated by Django 5.2.14 on 2026-08-14 07:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_backfill_primary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='package_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='package_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='packaging_factor',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'unités par conditionnement au moment de la vente.", null=True),
        ),
    ]
