# Generated by Django 6.0.1 on 2026-08-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_saleitem_package_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('credit', 'Crédit'), ('loyalty', 'Points de fidélité'), ('other', 'Autre')], default='cash', max_length=20),
        ),
    ]
