# Generated by Django 5.2.14 on 2026-08-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_paymentmethod_method_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('credit', 'Crédit'), ('loyalty', 'Points de fidélité'), ('advance', 'Avance client'), ('other', 'Autre')], default='cash', max_length=20),
        ),
    ]
