# Generated by Django 5.2.14 on 2026-08-28 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_customer_customers_organiz_832b53_idx_and_more'),
        ('inventory', '0018_stock_stocks_organiz_d6689f_idx_and_more'),
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('products', '0011_product_products_organiz_5d3d3a_idx_and_more'),
        ('sales', '0022_payment_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='payments_organiz_06026d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='sales_organiz_5d05db_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='sale_items_organiz_a76d94_idx'),
        ),
    ]
