"""
L'heure de l'ACTE, pas celle de son enregistrement.

`auto_now_add` posait la date à l'INSERTION serveur, si bien qu'une vente
encaissée hors ligne portait le jour de sa POUSSÉE : trois jours sans réseau
empilaient trois journées de recette sur celle du retour. Les champs de date
métier lisent désormais `apps.core.clock.maintenant`, que le répartiteur du
journal règle sur `occurred_at` le temps de rejouer l'acte.

**Aucune écriture en base** : `auto_now_add` comme `default=` sont des valeurs
d'application, pas de schéma. `sqlmigrate` rend « (no-op) » sur chacune.

`updated_at` n'est PAS concerné, et ne doit jamais l'être : c'est le curseur du
tirage, et le reculer rendrait la ligne invisible aux terminaux déjà passés.
"""
# Generated by Django 5.2.14 on 2026-09-01 14:06

import apps.core.clock
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_payment_payments_organiz_06026d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='registersession',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='registersession',
            name='opened_at',
            field=models.DateTimeField(default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='registersessioncurrencybalance',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='return_date',
            field=models.DateTimeField(default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='salereturnitem',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
    ]
