services:
  db:
    image: postgres:16
    container_name: vente_facile_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vente-facile-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vente_facile_backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
    networks:
      - vente-facile-network
             
networks:
  vente-facile-network:
    driver: bridge

volumes:
  postgres_data:
