services:
  db:
    image: postgres:16
    container_name: vente_facile_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vente-facile-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vente_facile_redis
    volumes:
      - redis_data:/data
    networks:
      - vente-facile-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vente_facile_backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - vente-facile-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vente_facile_celery_worker
    command: celery -A app worker --loglevel=info
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - vente-facile-network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vente_facile_celery_beat
    command: celery -A app beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    restart: unless-stopped
    networks:
      - vente-facile-network

networks:
  vente-facile-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
