# Generated by Django 5.2.10 on 2026-02-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_customer_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='customergroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customergroup',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='customergroup',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='group',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_email_92e882_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='linked_user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='price_list',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='CustomerGroup',
        ),
    ]
