# Generated by Django 5.2.10 on 2026-02-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_add_customer_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms',
        ),
    ]
