# Generated by Django 6.0.1 on 2026-06-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_supplier_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sync_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp used for sync conflict resolution. Can be set by client.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='synced_from_client',
            field=models.BooleanField(default=False, help_text='True if this record was created/updated via sync from mobile client'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sync_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp used for sync conflict resolution. Can be set by client.', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='synced_from_client',
            field=models.BooleanField(default=False, help_text='True if this record was created/updated via sync from mobile client'),
        ),
    ]
