# Generated by Django 5.2.14 on 2026-08-03 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_customer_sync_updated_at_customer_synced_from_client_and_more'),
        ('organizations', '0008_add_extra_permissions_to_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'created_at'], name='customer_org_created_idx'),
        ),
    ]
