# Generated by Django 5.2.14 on 2026-08-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_customer_customer_org_created_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
