# Generated by Django 6.0.1 on 2026-08-16 02:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_backfill_supplier_currency'),
        ('organizations', '0008_add_extra_permissions_to_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=12, default=Decimal('1'), max_digits=20),
        ),
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='contacts.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'db_table': 'customer_balances',
                'ordering': ['currency'],
                'indexes': [models.Index(fields=['organization', 'currency'], name='customer_ba_organiz_daacaf_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'currency'), name='unique_customer_balance_per_currency')],
            },
        ),
    ]
