# Generated by Django 5.2.14 on 2026-08-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_backfill_customer_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allow_credit',
            field=models.BooleanField(default=True),
        ),
    ]
