# Generated by Django 5.2.14 on 2026-08-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_customer_allow_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
