# Generated by Django 5.2.14 on 2026-08-28 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_customertransaction_receipt_number'),
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('sales', '0022_payment_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='customers_organiz_832b53_idx'),
        ),
        migrations.AddIndex(
            model_name='customertransaction',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='customer_tr_organiz_bb56f5_idx'),
        ),
    ]
