# Generated by Django 5.2.14 on 2026-08-25 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0008_add_extra_permissions_to_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='organizations.organization')),
            ],
            options={
                'db_table': 'document_sequences',
                'constraints': [models.UniqueConstraint(fields=('organization', 'prefix', 'year'), name='unique_document_sequence_per_org_prefix_year')],
            },
        ),
    ]
