# Generated by Django 5.2.10 on 2026-02-28 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_days', models.PositiveIntegerField(default=15, help_text="Nombre de jours de la période d'essai pour les nouveaux comptes")),
                ('grace_period_days', models.PositiveIntegerField(default=3, help_text='Nombre de jours de grâce après expiration avant blocage total')),
            ],
            options={
                'verbose_name': 'Configuration globale',
                'verbose_name_plural': 'Configuration globale',
                'db_table': 'global_config',
            },
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription'),
        ),
    ]
