# Generated by Django 6.0.1 on 2026-03-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_currency_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
