# Generated by Django 5.2.14 on 2026-08-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_moko_poll_interval_60s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
