# Generated by Django 5.2.14 on 2026-08-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_moko_reconcile_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='reconcile_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
