# Generated by Django 5.2.10 on 2026-02-02 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_initial'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockadjustment'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['organization', 'is_active'], name='warehouses_organiz_12fb1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['organization', 'status'], name='stock_trans_organiz_c33c35_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['reference'], name='stock_trans_referen_425057_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'product'], name='stock_movem_organiz_907225_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='stock_movem_movemen_d922c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='stock_movem_created_07bdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_movem_referen_a0d8b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklocation',
            unique_together={('warehouse', 'code')},
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='stock_batch_expiry__ed4ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['batch_number'], name='stock_batch_batch_n_8a9877_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockbatch',
            unique_together={('product', 'variant', 'warehouse', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['organization', 'status'], name='stock_adjus_organiz_62ec85_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['reference'], name='stock_adjus_referen_34be22_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['organization', 'product'], name='stocks_organiz_ad4dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['warehouse'], name='stocks_warehou_4f53a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'variant', 'warehouse', 'location')},
        ),
    ]
