# Generated by Django 5.2.10 on 2026-02-12 10:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_backfill_avg_cost'),
        ('organizations', '0003_alter_organization_options'),
        ('products', '0004_alter_product_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('scope_type', models.CharField(choices=[('full', 'Inventaire complet'), ('category', 'Par catégorie'), ('product', 'Par produit')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('review', 'En révision'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_stock_locked', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('total_expected_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('total_counted_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('total_difference_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('total_difference_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('categories', models.ManyToManyField(blank=True, related_name='inventory_sessions', to='products.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('products', models.ManyToManyField(blank=True, related_name='inventory_sessions', to='products.product')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_inventory_sessions', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sessions', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_expected', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('quantity_counted', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('quantity_difference', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('difference_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_counted', models.BooleanField(default=False)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_counts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_counts', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_counts', to='products.productvariant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='inventory.inventorysession')),
            ],
            options={
                'db_table': 'inventory_counts',
                'ordering': ['product__name'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['organization', 'status'], name='inventory_s_organiz_dc1e68_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['reference'], name='inventory_s_referen_da852c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['warehouse', 'status'], name='inventory_s_warehou_7b09a5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['session', 'is_counted'], name='inventory_c_session_9cd0a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycount',
            unique_together={('session', 'product', 'variant')},
        ),
    ]
