# Generated by Django 6.0.1 on 2026-03-14 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorysession_inventorycount_and_more'),
        ('organizations', '0004_simplify_roles'),
        ('products', '0005_remove_product_type_and_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysession',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='inventorysession',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='unique_inventory_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='unique_adjustment_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='unique_transfer_reference_per_org'),
        ),
    ]
