# Generated by Django 5.2.14 on 2026-08-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockmovement_sync_updated_at_and_more'),
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('products', '0008_product_sync_updated_at_product_synced_from_client_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['organization', 'warehouse'], name='stock_org_warehouse_idx'),
        ),
    ]
