# Generated by Django 5.2.14 on 2026-08-14 07:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stock_stock_org_warehouse_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='loose_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text="Part de `quantity` qui se trouve hors emballage scellé, pour les produits vendus en gros et au détail. Alimentée par les déconditionnements et les entrées saisies à l'unité. Sans objet pour les produits vendus au détail uniquement.", max_digits=15),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='input_loose_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='input_package_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='packaging_factor',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'unités par conditionnement au moment du mouvement.", null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Achat'), ('sale', 'Vente'), ('return_in', 'Retour client'), ('return_out', 'Retour fournisseur'), ('transfer_in', 'Transfert entrant'), ('transfer_out', 'Transfert sortant'), ('adjustment_in', 'Ajustement positif'), ('adjustment_out', 'Ajustement négatif'), ('damage', 'Dommage/Perte'), ('expired', 'Périmé'), ('initial', 'Stock initial'), ('production_in', 'Production entrante'), ('production_out', 'Production sortante'), ('unpack', 'Déconditionnement')], max_length=20),
        ),
    ]
