# Generated by Django 5.2.14 on 2026-08-14 08:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stock_loose_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='counted_loose_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='counted_package_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='expected_loose_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='packaging_factor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='counted_loose_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
