# Generated by Django 5.2.14 on 2026-08-14 12:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventorycount_counted_loose_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='counted_package_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='packaging_factor',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'unités par contenant au moment du comptage.", null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='loose_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='package_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='packaging_factor',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'unités par contenant au moment de la demande.", null=True),
        ),
    ]
