# Generated by Django 5.2.14 on 2026-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stockadjustmentitem_counted_package_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='input_loose_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat d'une unité de détail, tel que saisi.", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='input_package_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat d'un conditionnement, tel que saisi.", max_digits=15, null=True),
        ),
    ]
