# Generated by Django 5.2.14 on 2026-08-16 17:14

from decimal import Decimal
from django.db import migrations, models

ZERO = Decimal('0.000')


def backfill_package_quantity(apps, schema_editor):
    """
    Matérialise le nombre de conditionnements scellés, jusqu'ici dérivé.

    L'ancien modèle déduisait les scellés d'un total unique :
    ``(quantity - loose_quantity) // facteur``, le reste (dit *orphelin*)
    retombant au vrac. On rejoue exactement cette division une dernière fois
    pour figer les deux compteurs, sans changer aucun total : un stock de 48
    bouteilles dont 12 en vrac ressort à 3 casiers + 12 bouteilles.

    Les produits vendus au détail seul gardent leurs deux compteurs à zéro.
    """
    Stock = apps.get_model('inventory', 'Stock')

    stocks = (
        Stock.objects
        .select_related('product')
        .exclude(product__selling_mode='retail_only')
    )

    updated = []
    for stock in stocks.iterator(chunk_size=500):
        factor = stock.product.units_per_package or 0
        if factor < 2:
            continue

        quantity = Decimal(stock.quantity or 0)
        loose = max(ZERO, min(Decimal(stock.loose_quantity or 0), max(quantity, ZERO)))

        sealed_base = quantity - loose
        if sealed_base < 0:
            packages, loose = 0, quantity
        else:
            packages = int(sealed_base // factor)
            loose = loose + (sealed_base - packages * factor)

        stock.package_quantity = Decimal(packages).quantize(ZERO)
        stock.loose_quantity = loose.quantize(ZERO)
        updated.append(stock)

        if len(updated) >= 500:
            Stock.objects.bulk_update(updated, ['package_quantity', 'loose_quantity'])
            updated = []

    if updated:
        Stock.objects.bulk_update(updated, ['package_quantity', 'loose_quantity'])


def noop_reverse(apps, schema_editor):
    """
    Rien à défaire : `quantity` n'a pas bougé et reste le total de référence.
    Retirer la colonne suffit à revenir au partage dérivé.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockmovement_input_unit_costs'),
        # `selling_mode` / `units_per_package` sont lus par le backfill.
        ('products', '0009_product_allow_auto_unpacking_product_packaging_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='package_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text="Conditionnements encore scellés réellement présents (casiers, cartons). Compteur à part entière, pas une division de `quantity` : c'est ce qui permet de refuser une vente en gros quand il ne reste que des unités déjà sorties d'un emballage. Sans objet pour les produits vendus au détail uniquement.", max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='loose_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text="Unités hors emballage scellé (bouteilles à la pièce), pour les produits vendus en gros et au détail. Alimentée par les déconditionnements et les entrées saisies à l'unité. Sans objet pour les produits vendus au détail uniquement.", max_digits=15),
        ),
        migrations.RunPython(backfill_package_quantity, noop_reverse),
    ]
