# Generated by Django 5.2.14 on 2026-08-28 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_stockadjustmentitem_expected_loose_quantity'),
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('products', '0010_product_package_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='stocks_organiz_d6689f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='stock_movem_organiz_75120f_idx'),
        ),
    ]
