# Generated by Django 5.2.10 on 2026-02-21 05:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0006_remove_supplier_unused_fields'),
        ('organizations', '0004_simplify_roles'),
        ('products', '0004_alter_product_unique_together_and_more'),
        ('sales', '0004_add_receipt_printed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_points_earned', models.PositiveIntegerField(default=0)),
                ('total_points_redeemed', models.PositiveIntegerField(default=0)),
                ('current_points', models.IntegerField(default=0)),
                ('tier', models.CharField(blank=True, default='', max_length=50)),
                ('last_points_earned_at', models.DateTimeField(blank=True, null=True)),
                ('last_points_redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='contacts.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Customer loyalties',
                'db_table': 'customer_loyalty',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Programme de fidélité', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('points_calculation_type', models.CharField(choices=[('fixed_per_amount', 'Points fixes par montant'), ('percentage', 'Pourcentage du montant')], default='fixed_per_amount', max_length=20)),
                ('points_per_unit', models.PositiveIntegerField(default=1, help_text='Nombre de points gagnés')),
                ('amount_per_unit', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Montant requis pour gagner les points (en devise principale)', max_digits=15)),
                ('points_percentage', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Pourcentage du montant converti en points', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('point_value', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text="Valeur d'un point en devise principale (pour les récompenses)", max_digits=10)),
                ('min_points_to_redeem', models.PositiveIntegerField(default=100, help_text='Nombre minimum de points pour pouvoir les utiliser')),
                ('points_expiry_days', models.PositiveIntegerField(default=0, help_text='Nombre de jours avant expiration des points (0 = jamais)')),
                ('only_registered_customers', models.BooleanField(default=True, help_text='Seuls les clients enregistrés peuvent accumuler des points')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'db_table': 'loyalty_programs',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[('discount_amount', 'Réduction montant fixe'), ('discount_percentage', 'Réduction pourcentage'), ('free_product', 'Produit gratuit'), ('custom', 'Récompense personnalisée')], default='discount_amount', max_length=20)),
                ('points_required', models.PositiveIntegerField(help_text='Nombre de points requis pour cette récompense')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_active', models.BooleanField(default=True)),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='settings.loyaltyprogram')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_rewards', to='products.product')),
            ],
            options={
                'db_table': 'loyalty_rewards',
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Points gagnés'), ('redeem', 'Points utilisés'), ('expire', 'Points expirés'), ('adjust', 'Ajustement manuel'), ('bonus', 'Bonus')], max_length=20)),
                ('points', models.IntegerField(help_text='Positif pour gain, négatif pour utilisation')),
                ('balance_after', models.IntegerField(help_text='Solde de points après la transaction')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('customer_loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='settings.customerloyalty')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='settings.loyaltyreward')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='sales.sale')),
            ],
            options={
                'db_table': 'loyalty_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCurrency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Taux de change par rapport à la devise principale', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('is_active', models.BooleanField(default=True)),
                ('last_rate_update', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_currencies', to='settings.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'db_table': 'organization_currencies',
                'ordering': ['-is_primary', 'currency__code'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_header', models.TextField(blank=True, help_text='En-tête des reçus')),
                ('receipt_footer', models.TextField(blank=True, help_text='Pied de page des reçus')),
                ('allow_negative_stock_sales', models.BooleanField(default=False, help_text='Autoriser les ventes même si le stock est insuffisant')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taux de TVA par défaut (%)', max_digits=5)),
                ('show_secondary_currency_on_receipt', models.BooleanField(default=False, help_text='Afficher le montant en devise secondaire sur les reçus')),
                ('auto_update_exchange_rates', models.BooleanField(default=False, help_text='Mettre à jour automatiquement les taux de change')),
                ('show_loyalty_points_on_receipt', models.BooleanField(default=True, help_text='Afficher les points de fidélité sur les reçus')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text="Seuil d'alerte de stock bas")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Organization settings',
                'db_table': 'organization_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='customerloyalty',
            constraint=models.UniqueConstraint(fields=('organization', 'customer'), name='unique_loyalty_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyprogram',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_loyalty_program_per_org'),
        ),
        migrations.AddConstraint(
            model_name='organizationcurrency',
            constraint=models.UniqueConstraint(fields=('organization', 'currency'), name='unique_currency_per_org'),
        ),
        migrations.AddConstraint(
            model_name='organizationsettings',
            constraint=models.UniqueConstraint(fields=('organization',), name='unique_settings_per_org'),
        ),
    ]
