# Generated by Django 5.2.10 on 2026-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_add_all_supported_currencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='allow_negative_stock_sales',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='auto_update_exchange_rates',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='default_tax_rate',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='show_secondary_currency_on_receipt',
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='show_loyalty_points_on_receipt',
            field=models.BooleanField(default=True, help_text='Afficher les points gagnés et le solde du client sur les reçus'),
        ),
    ]
