# Generated by Django 6.0.1 on 2026-03-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_remove_deprecated_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='receipt_paper_width',
            field=models.PositiveIntegerField(default=58, help_text='Largeur du papier du ticket en mm (58 ou 80)'),
        ),
    ]
