# Generated by Django 6.0.1 on 2026-05-27 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('sales', '0011_alter_saleitem_tax_rate'),
        ('settings', '0006_add_receipt_paper_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn', 'Points gagnés'), ('redeem', 'Points utilisés'), ('expire', 'Points expirés'), ('adjust', 'Ajustement manuel'), ('bonus', 'Bonus'), ('earn_reversal', 'Annulation gain'), ('redeem_reversal', 'Annulation utilisation')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type__in', ['earn', 'redeem', 'earn_reversal', 'redeem_reversal'])), fields=('sale', 'transaction_type'), name='loyalty_tx_unique_per_sale_type'),
        ),
    ]
