# Generated by Django 6.0.1 on 2026-08-09 22:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_loyaltytransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcurrency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=12, default=Decimal('1.000000'), help_text='Taux de change par rapport à la devise principale', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-12'))]),
        ),
    ]
