# Generated by Django 6.0.1 on 2026-08-16 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('sales', '0020_alter_paymentmethod_method_type'),
        ('settings', '0009_ensure_primary_organization_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loyaltytransaction',
            name='loyalty_tx_unique_per_sale_type',
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='sales.payment'),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type__in', ['earn', 'earn_reversal', 'redeem_reversal'])), fields=('sale', 'transaction_type'), name='loyalty_tx_unique_per_sale_type'),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', True), ('transaction_type', 'redeem')), fields=('sale',), name='loyalty_tx_unique_sale_redeem_at_creation'),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False), ('transaction_type', 'redeem')), fields=('payment',), name='loyalty_tx_unique_payment_redeem'),
        ),
    ]
