# Generated by Django 5.2.14 on 2026-08-17 00:36
"""
Points de fidélité fractionnaires.

Les compteurs étaient des entiers : 1 % d'un panier de 58 USD valait 0,58 point,
tronqué à **zéro**. Sur une organisation dont la devise principale a une valeur
unitaire élevée, la fidélité ne créditait donc quasiment jamais rien, et un
panier de 396 USD perdait au passage 0,96 point.

Aucune reprise de données n'est nécessaire : l'élargissement `integer` →
`numeric(15, 2)` est fait par Postgres sans perte (un solde de 3 devient 3.00).
Les contraintes `PositiveIntegerField` sur les cumuls à vie disparaissent au
passage ; le bornage à zéro reste assuré par `CustomerLoyalty.reverse_points`.
"""

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_schedule_loyalty_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloyalty',
            name='current_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='customerloyalty',
            name='total_points_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='customerloyalty',
            name='total_points_redeemed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, help_text='Solde de points après la transaction', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='points',
            field=models.DecimalField(decimal_places=2, help_text='Positif pour gain, négatif pour utilisation', max_digits=15),
        ),
    ]
