# Generated by Django 5.2.14 on 2026-08-17 11:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_alter_customerloyalty_current_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='max_redemption_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text="Part maximale d'une facture réglable en points (100 = pas de plafond)", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
