# Generated by Django 5.2.14 on 2026-08-17 12:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


CEILING = Decimal('70.00')


def cap_existing_programs(apps, schema_editor):
    """
    Ramène à la borne les programmes déjà configurés au dessus.

    Le validator ne s'applique qu'aux écritures futures : sans ce passage, une
    organisation restée à 100 % continuerait de laisser solder une facture
    entière en points jusqu'à sa prochaine sauvegarde.
    """
    LoyaltyProgram = apps.get_model('settings', 'LoyaltyProgram')
    LoyaltyProgram.objects.filter(
        max_redemption_percent__gt=CEILING,
    ).update(max_redemption_percent=CEILING)


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_loyaltyprogram_max_redemption_percent'),
    ]

    operations = [
        migrations.RunPython(cap_existing_programs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='max_redemption_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text="Part maximale d'une facture réglable en points (maximum 70 %)", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('70.00'))]),
        ),
    ]
