# Generated by Django 5.2.14 on 2026-08-28 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('users', '0002_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('seq', models.BigIntegerField()),
                ('payload', models.JSONField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('applied', 'Appliquée'), ('duplicate', 'Doublon'), ('rejected', 'Refusée'), ('retry', 'À réessayer'), ('blocked', 'Bloquée')], max_length=12)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='users.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_operations',
                'ordering': ['received_at'],
                'indexes': [models.Index(fields=['organization', 'device', 'received_at'], name='sync_operat_organiz_05dcc7_idx'), models.Index(fields=['organization', 'verdict'], name='sync_operat_organiz_338d7c_idx')],
            },
        ),
    ]
