# Generated by Django 5.2.10 on 2026-02-02 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dashboards',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('metric', 'Métrique'), ('chart', 'Graphique'), ('table', 'Tableau'), ('list', 'Liste')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('position_x', models.PositiveSmallIntegerField(default=0)),
                ('position_y', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=1)),
                ('height', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'dashboard_widgets',
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/exports/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('sales', 'Ventes'), ('purchases', 'Achats'), ('inventory', 'Inventaire'), ('financial', 'Financier'), ('customer', 'Clients'), ('supplier', 'Fournisseurs'), ('product', 'Produits'), ('custom', 'Personnalisé')], max_length=20)),
                ('query_config', models.JSONField(default=dict)),
                ('columns', models.JSONField(default=list)),
                ('filters', models.JSONField(default=list)),
                ('grouping', models.JSONField(default=list)),
                ('sorting', models.JSONField(default=list)),
                ('chart_config', models.JSONField(blank=True, default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'report_templates',
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parameters', models.JSONField(default=dict)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('once', 'Une fois'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='once', max_length=20)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('schedule_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recipients', models.JSONField(default=list)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saved_reports',
            },
        ),
    ]
