# Generated by Django 5.2.10 on 2026-02-13 10:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0006_remove_supplier_unused_fields'),
        ('organizations', '0004_simplify_roles'),
        ('purchases', '0003_alter_purchaseorder_unique_together_and_more'),
        ('sales', '0003_alter_register_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('budget_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Budget mensuel alloué à cette catégorie (0 = pas de limite)', max_digits=15)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'db_table': 'expense_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Approuvée'), ('paid', 'Payée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('beneficiary', models.CharField(blank=True, help_text='Nom du bénéficiaire de la dépense', max_length=255)),
                ('payment_reference', models.CharField(blank=True, help_text='Référence du paiement (n° chèque, transaction mobile, etc.)', max_length=100)),
                ('expense_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Dépense récurrente (loyer, salaires, etc.)')),
                ('recurrence_period', models.CharField(blank=True, choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, help_text='Pièce justificative (facture, reçu, etc.)', null=True, upload_to='expenses/attachments/%Y/%m/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='sales.paymentmethod')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='cashbook.expensecategory')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=50)),
                ('direction', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=3)),
                ('movement_type', models.CharField(choices=[('sale', 'Vente'), ('sale_return', 'Remboursement client'), ('expense', 'Dépense'), ('purchase', 'Achat fournisseur'), ('supplier_refund', 'Remboursement fournisseur'), ('debt_collection', 'Recouvrement dette'), ('fund_in', 'Apport de fonds'), ('fund_out', 'Retrait de fonds'), ('adjustment', 'Ajustement de caisse'), ('other_in', 'Autre entrée'), ('other_out', 'Autre sortie')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=500)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solde de caisse après ce mouvement', max_digits=15)),
                ('movement_date', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='contacts.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='sales.paymentmethod')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='purchases.purchaseorder')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='sales.sale')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='contacts.supplier')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='cashbook.expense')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'db_table': 'cash_movements',
                'ordering': ['-movement_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'direction'], name='cash_moveme_organiz_9aafa4_idx'), models.Index(fields=['organization', 'movement_type'], name='cash_moveme_organiz_f8fdb8_idx'), models.Index(fields=['organization', 'movement_date'], name='cash_moveme_organiz_21c3e1_idx'), models.Index(fields=['reference'], name='cash_moveme_referen_b82267_idx'), models.Index(fields=['organization', 'is_cancelled'], name='cash_moveme_organiz_37baec_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'reference'), name='unique_cash_movement_reference_per_org')],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_expense_category_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'status'], name='expenses_organiz_eafefa_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'category'], name='expenses_organiz_5cf845_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='expenses_expense_43600a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['reference'], name='expenses_referen_d421ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='unique_expense_reference_per_org'),
        ),
    ]
