# Generated by Django 5.2.10 on 2026-02-17 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
        ('organizations', '0004_simplify_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='expense_category',
            field=models.ForeignKey(blank=True, help_text='Catégorie pour les sorties de caisse (hors dépenses formelles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_cash_movements', to='cashbook.expensecategory'),
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#10B981', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': "Catégorie d'entrée",
                'verbose_name_plural': "Catégories d'entrées",
                'db_table': 'income_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='income_category',
            field=models.ForeignKey(blank=True, help_text='Catégorie pour les entrées de caisse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='cashbook.incomecategory'),
        ),
        migrations.AddConstraint(
            model_name='incomecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_income_category_name_per_org'),
        ),
    ]
