# Generated by Django 6.0.1 on 2026-06-06 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0003_expense_warehouse'),
        ('sales', '0011_alter_saleitem_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='sales.registersession'),
        ),
    ]
