# Generated by Django 5.2.14 on 2026-08-03 22:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0004_cashmovement_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Unités de devise principale pour 1 unité de `currency`.', max_digits=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Unités de devise principale pour 1 unité de `currency`.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale', 'Vente'), ('sale_return', 'Remboursement client'), ('expense', 'Dépense'), ('purchase', 'Achat fournisseur'), ('supplier_refund', 'Remboursement fournisseur'), ('debt_collection', 'Recouvrement dette'), ('fund_in', 'Apport de fonds'), ('fund_out', 'Retrait de fonds'), ('adjustment', 'Ajustement de caisse'), ('change', 'Monnaie rendue'), ('other_in', 'Autre entrée'), ('other_out', 'Autre sortie')], max_length=30),
        ),
    ]
