# Generated by Django 6.0.1 on 2026-08-09 22:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0006_backfill_multicurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=12, default=Decimal('1.000000'), help_text='Unités de devise principale pour 1 unité de `currency`.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=12, default=Decimal('1.000000'), help_text='Unités de devise principale pour 1 unité de `currency`.', max_digits=20),
        ),
    ]
