# Generated by Django 5.2.14 on 2026-08-28 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0009_realign_mismatched_currency'),
        ('contacts', '0014_customertransaction_receipt_number'),
        ('inventory', '0017_stockadjustmentitem_expected_loose_quantity'),
        ('organizations', '0008_add_extra_permissions_to_membership'),
        ('purchases', '0006_goodsreceiptitem_loose_quantity_and_more'),
        ('sales', '0022_payment_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='cash_moveme_organiz_4bb584_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'updated_at', 'id'], name='expenses_organiz_23c2e7_idx'),
        ),
    ]
