# Generated by Django 5.2.10 on 2026-02-02 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_initial'),
        ('inventory', '0004_initial'),
        ('organizations', '0002_initial'),
        ('products', '0002_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='contacts.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='purchase_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='purchases.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='contacts.supplier'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasereturn'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.paymentmethod'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contacts.supplier'),
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchases.supplierpayment'),
        ),
        migrations.AddField(
            model_name='supplierpaymentallocation',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='purchases.purchaseorder'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', 'status'], name='purchase_or_organiz_6d8f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', 'supplier'], name='purchase_or_organiz_bf5864_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['reference'], name='purchase_or_referen_cf91c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('organization', 'reference')},
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['organization', 'status'], name='goods_recei_organiz_09d529_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['reference'], name='goods_recei_referen_09701f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order'], name='purchase_or_purchas_a61376_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['product'], name='purchase_or_product_357a28_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['organization', 'status'], name='purchase_re_organiz_23add3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['reference'], name='purchase_re_referen_15dabb_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['organization', 'supplier'], name='supplier_pa_organiz_0066a7_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['reference'], name='supplier_pa_referen_3d8c82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierpaymentallocation',
            unique_together={('payment', 'purchase_order')},
        ),
    ]
