# Generated by Django 5.2.10 on 2026-02-03 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_customer_unique_together_and_more'),
        ('inventory', '0005_alter_warehouse_unique_together_and_more'),
        ('organizations', '0003_alter_organization_options'),
        ('purchases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'reference'), name='unique_purchase_order_reference_per_org'),
        ),
    ]
