# Generated by Django 5.2.14 on 2026-08-14 01:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchaseorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=12, default=Decimal('1.000000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=12, default=Decimal('1.000000'), max_digits=20),
        ),
    ]
