# Generated by Django 5.2.14 on 2026-08-14 12:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_backfill_primary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='loose_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='package_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='package_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat d'un contenant entier. `unit_cost` en est déduit et reste la valeur utilisée pour le coût moyen pondéré.", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='packaging_factor',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'unités par contenant au moment de la réception.", null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='loose_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='package_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='package_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='packaging_factor',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'unités par contenant au moment de la commande.", null=True),
        ),
    ]
