# Generated by Django 5.2.10 on 2026-02-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'permissions': [('manage_organization', 'Can manage organization')]},
        ),
    ]
