# Generated by Django 5.2.10 on 2026-02-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Admin'), ('manager', 'Gérant'), ('stock_keeper', 'Magasinier'), ('cashier', 'Caissier')], default='cashier', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Admin'), ('manager', 'Gérant'), ('stock_keeper', 'Magasinier'), ('cashier', 'Caissier')], default='cashier', max_length=20),
        ),
    ]
