# Generated by Django 5.2.13 on 2026-05-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_membership_warehouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipwarehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
