# Generated by Django 6.0.1 on 2026-05-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_membershipwarehouse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=list, help_text='Permissions additionnelles accordées à cet utilisateur en plus de celles de son rôle.'),
        ),
    ]
