"""
L'heure de l'ACTE, pas celle de son enregistrement.

`auto_now_add` posait la date à l'INSERTION serveur, si bien qu'une vente
encaissée hors ligne portait le jour de sa POUSSÉE : trois jours sans réseau
empilaient trois journées de recette sur celle du retour. Les champs de date
métier lisent désormais `apps.core.clock.maintenant`, que le répartiteur du
journal règle sur `occurred_at` le temps de rejouer l'acte.

**Aucune écriture en base** : `auto_now_add` comme `default=` sont des valeurs
d'application, pas de schéma. `sqlmigrate` rend « (no-op) » sur chacune.

`updated_at` n'est PAS concerné, et ne doit jamais l'être : c'est le curseur du
tirage, et le reculer rendrait la ligne invisible aux terminaux déjà passés.
"""
# Generated by Django 5.2.14 on 2026-09-01 14:06

import apps.core.clock
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_add_extra_permissions_to_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='membershipwarehouse',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=apps.core.clock.maintenant, editable=False),
        ),
    ]
