# Generated by Django 5.2.10 on 2026-02-02 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock bas'), ('out_of_stock', 'Rupture de stock'), ('expiring_product', 'Produit bientôt périmé'), ('expired_product', 'Produit périmé'), ('payment_due', 'Paiement dû'), ('payment_overdue', 'Paiement en retard'), ('subscription_expiring', 'Abonnement expire bientôt'), ('subscription_expired', 'Abonnement expiré'), ('credit_limit', 'Limite de crédit atteinte'), ('system', 'Système')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Bas'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('acknowledged', 'Accusé'), ('resolved', 'Résolu'), ('dismissed', 'Ignoré')], default='active', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock bas'), ('out_of_stock', 'Rupture de stock'), ('expiring_product', 'Produit bientôt périmé'), ('expired_product', 'Produit périmé'), ('payment_due', 'Paiement dû'), ('payment_overdue', 'Paiement en retard'), ('subscription_expiring', 'Abonnement expire bientôt'), ('subscription_expired', 'Abonnement expiré'), ('credit_limit', 'Limite de crédit atteinte'), ('system', 'Système')], max_length=30)),
                ('conditions', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('low', 'Bas'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('notify_channels', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_minutes', models.PositiveIntegerField(default=60)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alert_rules',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échoué'), ('bounced', 'Rebondi')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('alert', 'Alerte')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-App')], default='in_app', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
    ]
